import {
    Ban,
    Bike,
    Bitcoin,
    Bot,
    Briefcase,
    Building2,
    Bus,
    Car,
    Castle,
    ChartLine,
    CircleDollarSign,
    CircleHelp,
    CloudLightning,
    CloudRain,
    Coffee,
    Compass,
    Cookie,
    CookingPot,
    Crown,
    CupSoda,
    Dices,
    Dumbbell,
    Factory,
    Flag,
    Footprints,
    Frown,
    Gamepad2,
    Gift,
    GraduationCap,
    HandCoins,
    Heart,
    HeartHandshake,
    HelpingHand,
    Home,
    ImageOff,
    Landmark,
    Medal,
    Meh,
    MessageCircleWarning,
    MicVocal,
    Monitor,
    Moon,
    ParkingSquare,
    PartyPopper,
    PawPrint,
    PhoneOff,
    Pill,
    Receipt,
    Rocket,
    Ship,
    ShoppingBag,
    ShoppingCart,
    Skull,
    Smartphone,
    Smile,
    Sparkles,
    Store,
    Tent,
    Thermometer,
    Ticket,
    TrainFront,
    TrendingDown,
    TrendingUp,
    Trophy,
    TriangleAlert,
    Users,
    Utensils,
    Video,
    Wine,
    Zap,
    type LucideIcon,
} from "lucide-react";
import type {BirthFamilyId, CompanyTypeId, EventId, GoodId, PartnerId, RankTier} from "@/types/game";

export const GOOD_ICONS: Record<GoodId, LucideIcon> = {
    chips: Cookie,
    vitasoy: CupSoda,
    phone: Smartphone,
    sneakers: Footprints,
    bitcoin: Bitcoin,
    gold: Medal,
    ev: Car,
    options: ChartLine,
};

export const COMPANY_ICONS: Record<CompanyTypeId, LucideIcon> = {
    bubble_tea: Coffee,
    claw_arcade: Gamepad2,
    esports: Monitor,
    ghost_kitchen: CookingPot,
    tutoring: GraduationCap,
    feng_shui: Compass,
    live_commerce: Video,
    ai_startup: Bot,
    crypto_exchange: Landmark,
    parking_empire: ParkingSquare,
    property: Building2,
};

export const PARTNER_ICONS: Record<PartnerId, LucideIcon> = {
    mary: Smile,
    jenny: Heart,
    jessica: Crown,
};

export const EVENT_ICONS: Record<EventId, LucideIcon> = {
    snack_boom: Zap,
    crypto_crash: TrendingDown,
    windfall: Dices,
    collapse: Frown,
    nothing: Meh,
    vitasoy_craze: CupSoda,
    phone_hype: Smartphone,
    sneaker_frenzy: Footprints,
    gold_rush: Medal,
    ev_subsidy: Car,
    options_moon: TrendingUp,
    phone_brick: PhoneOff,
    gold_dump: TrendingDown,
    options_wipeout: Ban,
    sneaker_flop: TrendingDown,
    ev_price_war: TrendingDown,
    chips_recall: Cookie,
    bitcoin_moon: Rocket,
    gov_cash: HandCoins,
    landlord_rage: Home,
    scam_course: TriangleAlert,
    lai_see: Gift,
    food_poisoning: Pill,
    overtime_bonus: Sparkles,
    spa_reboot: Heart,
    typhoon_rest: CloudRain,
    gym_trap: Dumbbell,
    mtr_apology: TrainFront,
    relative_borrow: Users,
    lucky_draw: PartyPopper,
    whatsapp_scam: MessageCircleWarning,
    banquet_debt: Wine,
    black_rain_bonus: CloudLightning,
    parking_fine: Ticket,
    stock_group_trap: TriangleAlert,
    viral_milk_tea: CupSoda,
    nft_jpeg: ImageOff,
    dentist_shock: Pill,
    karaoke_overtime: MicVocal,
    octopus_stuck: TrainFront,
    haidilao_birthday: PartyPopper,
    bus_uncle: Bus,
    side_hustle_delivery: Bike,
    flu_wave: Thermometer,
    cross_border_shop: ShoppingBag,
    electricity_hike: Zap,
    mahjong_night: Dices,
    yum_cha_sunday: Utensils,
    aed_queue: Pill,
    wfh_commute_save: Home,
    sneakers_collab: Footprints,
    gold_cny: Medal,
    options_fomc: ChartLine,
    phone_trade_in_scam: PhoneOff,
    chips_bar_promo: Cookie,
    bitcoin_etf_rumor: Bitcoin,
    vitasoy_heatwave: CupSoda,
    ev_charger_queue: Car,
    red_packet_war: Gift,
    night_market_win: Store,
    office_layoff_rumor: Briefcase,
    tax_return: Receipt,
    mid_autumn_box: Moon,
    double_eleven_sale: ShoppingCart,
    hospital_bill: Pill,
    ferry_cancel: Ship,
    wet_market_auntie: ShoppingBag,
    blood_donate: Heart,
    flag_day: Flag,
    food_bank_shift: HandCoins,
    elderly_visit: HeartHandshake,
    scholarship_fund: GraduationCap,
    stray_rescue: PawPrint,
    community_chest: HandCoins,
    typhoon_shelter_help: CloudRain,
    corporate_donation: Landmark,
    anonymous_kindness: HelpingHand,
    organ_donor_card: HeartHandshake,
    park_cleanup: Sparkles,
};

export const BIRTH_FAMILY_ICONS: Record<BirthFamilyId, LucideIcon> = {
    low_class: Tent,
    middle_class: Home,
    high_class: Castle,
};

export const RANK_ICONS: Record<RankTier, LucideIcon> = {
    winner: Trophy,
    almost: Footprints,
    middle: Home,
    bottom: Frown,
};

export const BrandIcon = CircleDollarSign;
export const MarketSectionIcon = ShoppingCart;
export const CompanySectionIcon = Factory;
export const FamilySectionIcon = HeartHandshake;
export const HeartIcon = Heart;
export const ConfirmDangerIcon = TriangleAlert;
export const ConfirmHelpIcon = CircleHelp;
export const DeathIcon = Skull;
export const RetireIcon = PartyPopper;
